import { useEffect, useState } from 'react';
import { fetchWeeklySnapshot, type WeeklySnapshot } from '../api';

function StatTile({ value, label, sub }: { value: string | number; label: string; sub?: string }) {
  return (
    <div className="bg-white rounded-xl border border-slate-200 p-5">
      <div className="text-3xl font-extrabold text-slate-800 leading-none">{value}</div>
      <div className="text-[12px] text-slate-400 mt-1.5">{label}</div>
      {sub && <div className="text-[11px] font-semibold text-emerald-500 mt-1">{sub}</div>}
    </div>
  );
}

export default function WeeklySummaryView() {
  const [snap, setSnap] = useState<WeeklySnapshot | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    fetchWeeklySnapshot()
      .then(setSnap)
      .catch((e) => setError(e.message || 'Failed to load'))
      .finally(() => setLoading(false));
  }, []);

  if (loading) {
    return (
      <div className="flex items-center justify-center h-48 text-slate-400 text-sm">
        Loading weekly report from Reporter agent…
      </div>
    );
  }

  if (error || !snap) {
    return (
      <div className="rounded-lg border border-red-200 bg-red-50 px-5 py-4 text-[13px] text-red-700">
        {error || 'No data returned.'} Make sure the backend is running.
      </div>
    );
  }

  const employees = Object.entries(snap.by_employee);

  return (
    <div className="flex flex-col gap-5">
      {/* Header */}
      <div>
        <h2 className="text-[18px] font-bold text-slate-800">Weekly Summary</h2>
        <p className="text-[12px] text-slate-400 mt-0.5">
          Last {snap.period_days} days — generated by the Reporter agent
        </p>
      </div>

      {/* Stats row */}
      <div className="grid grid-cols-4 gap-3">
        <StatTile value={snap.total_check_ins} label="Check-ins processed" />
        <StatTile
          value={snap.risk_flags}
          label="Risk flags raised"
          sub={snap.risk_flags === 0 ? '✓ clean week' : undefined}
        />
        <StatTile value={snap.total_events} label="Total agent events" />
        <StatTile value={`${snap.period_days}d`} label="Period covered" />
      </div>

      {/* Per-employee breakdown */}
      <div>
        <div className="text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-3">
          By team member
        </div>
        {employees.length === 0 ? (
          <p className="text-[13px] text-slate-400">No team activity in this period.</p>
        ) : (
          <div className="flex flex-col gap-2">
            {employees.map(([name, data]) => {
              const hasRisks = data.risks.length > 0;
              return (
                <div
                  key={name}
                  className={`bg-white rounded-xl border px-5 py-4 flex items-center justify-between ${
                    hasRisks ? 'border-l-4 border-l-amber-400 border-slate-200' : 'border-slate-200'
                  }`}
                >
                  <div>
                    <div className="text-[14px] font-semibold text-slate-800">{name}</div>
                    <div className="text-[12px] text-slate-400 mt-0.5">
                      {data.checkIns.length} check-in{data.checkIns.length !== 1 ? 's' : ''}
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {hasRisks ? (
                      <span className="text-[11px] font-semibold bg-amber-50 text-amber-600 px-2.5 py-1 rounded-full">
                        {data.risks.length} risk{data.risks.length !== 1 ? 's' : ''}
                      </span>
                    ) : (
                      <span className="text-[11px] font-semibold bg-emerald-50 text-emerald-600 px-2.5 py-1 rounded-full">
                        ✓ no risks
                      </span>
                    )}
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </div>

      {/* Recent events */}
      {snap.events.length > 0 && (
        <div>
          <div className="text-[11px] font-bold text-slate-500 uppercase tracking-wider mb-3">
            Recent events ({snap.events.length})
          </div>
          <div className="bg-white rounded-xl border border-slate-200 divide-y divide-slate-100">
            {snap.events.slice(0, 20).map((ev: any, i: number) => (
              <div key={i} className="px-5 py-3 flex items-start gap-3">
                <span className="text-[10px] font-mono text-slate-400 mt-0.5 flex-shrink-0 w-16">
                  {ev.timestamp
                    ? new Date(ev.timestamp).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })
                    : '—'}
                </span>
                <span className="text-[12px] text-slate-600 leading-relaxed">
                  {ev.summary || ev.description || ev.text || JSON.stringify(ev)}
                </span>
              </div>
            ))}
            {snap.events.length > 20 && (
              <div className="px-5 py-3 text-[12px] text-slate-400">
                + {snap.events.length - 20} more events
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}
